package Constants;

public class Const {
    public static final String MAIN_URL = "https://xpertesy.com/",
            GET_STARTED_BUTTON = "//*[@class='button ripple-effect home-index-login input-user-type-biz popup-with-zoom-anim']",
            INTRO_BANNER = "//*[@class = 'intro-banner dark-overlay big-padding']",
            TEXT_CONTENT = "//*[@class='text-content']",
            LEARN_MORE_BUTTON = "//*[@class='col-6 text-right']//descendant::*[@class='button ripple-effect']",
            GMAIL_HEADER = "//*[text()='Sign in']",
            CREATE_ACC = "//*[text() = 'Create account']",
            TOP_MENU_LOGO_BUTTON = "//*[@id ='logo']",
            TOP_MENU_HOME_BUTTON = "//*[text() = 'Home']",
            TOP_MENU_BUSINESS_BUTTON = "//*[text() = 'Business']",
            TOP_MENU_EDUCATION_BUTTON = "//*[text() = 'Education']",
            TOP_MENU_FAMILY_BUTTON = "//*[text() = 'Family']",
            TOP_MENU_FOR_OFFICES_BUTTON = "//*[text() = 'for Offices']",
            TOP_MENU_FOR_OFFICES_DD_LEARN_MORE_BUTTON = "//a[text() = 'Learn More']",
            TOP_MENU_FOR_OFFICES_DD_ADMIN_BUTTON = "//a[text() = 'Admin']",
            TOP_MENU_FOR_OFFICES_DD_MEETING_ROOMS_BUTTON = "//a[text() = 'Meeting Rooms']",
            TOP_MENU_CONTACT_US_BUTTON = "//*[text() = 'Contact Us']",
            BOTTOM_MENU_ABOUT_LINK = "//SPAN[text() = 'About']",
            BOTTOM_MENU_CONTACT_US_LINK = "//SPAN[text() = 'Contact Us']",
            BOTTOM_MENU_PRIVACY_LINK = "//SPAN[text() = 'Privacy']",
            BOTTOM_MENU_TERMS_OF_USE_LINK = "//SPAN[text() = 'Terms of Use']",
            LEARN_MORE_HEADER = "//*[@class='pt-0 pb-lg-0']//descendant::*[@class='item-description-headline main-page-title-side']",
            ACCOUNT_ICON = "//img[@src ='images/user-avatar-placeholder.png']",
            SEND_BUTTON = "//*[@class= 'button full-width button-sliding-icon'] [@type='submit'] [@form='forgotpass-form']",
            FORGOT_PASSWORD_HEADER = "//*[@class='popup-tab-content']//descendant::*[@class='welcome-text']",
            FORGOT_PASSWORD_TEXT = "//*[@class='welcome-text']//descendant::*[text()='Forgot Password?']",
            ALMOST_THERE_NOTIFICATION = "//*[@class='success-modal']//descendant::*[@class='mt-5 pl-4 pr-4 text-center']",
            ALMOST_THERE_HEADER = "//*[@class='mfp-content']//descendant::*[@id='sign-in-dialog']",
            ALMOST_THERE_NOTIFICATION_CLOSE_BUTTON = "//*[@title='Close (Esc)'] [@type='button'] [@class='close-success mfp-close']",
            BACK_LOGIN_BUTTON = "//*[@id ='backtologin'] [@class='forgot-password auth-bottom']",
            PASSWORD_HEADER = "//*[@id='password-login']",
            LOG_IN_BUTTON = "//*[@form = 'login-form']",
            PASS_INPUT = "//*[@id = 'password-login']",
            FORGOT_PASSWORD_BUTTON = "//*[@id='forgotpass'] [@class='forgot-password auth-bottom']",
            REMEMBER_ME_CHECK_BOX = "//*[@class='auth-bottom checkbox d-block remember-me-container']//descendant::*[@class='margin-bottom-0']",
            INCORRECT_USERNAME_OR_PASSWORD_ERR = "//*[@class='closeable error notification'] [@id='login-notification']",
            INCORRECT_USERNAME_OR_PASSWORD_ERR_CLOSE_BUTTON = "//*[@class='closeable error notification']//descendant::*[@class='close']",
            FILL_OUT_THIS_FIELD_ERR = "//input[@type='hidden'] [@name='user-type'] [@value='2']",
            EYE_ICON = "//*[@class='input-with-icon-left']//descendant::*[@class='icon-feather-eye']",
            YOUR_EMAIL_ADDRESS_HEADER = "//*[text()= 'Your email address']",
            YOUR_EMAIL_ADDRESS_WINDOW_TAB_CONTENT = "//*[@class='popup-tab-content']",
            EMAIL_INPUT = "//*[@name = 'emailaddress-start']",
            CONTINUE_BUTTON = "//*[@class = 'button full-width button-sliding-icon']",
            CLOSE_BUTTON = "//*[@class='sign-in-form']//descendant::*[@type='button']",
            CONTINUE_WITH_GOOGLE_BUTTON = "//*[@class = 'google-login ripple-effect']",
            ERROR_TEXT = "//head//ancestor::*[@type='text/css']",
            YOUR_NAME_INPUT = "//*[@class = 'col-md-6 mb-3']//descendant::*[@id='name']",
            SUBJECT_INPUT = "//*[@class='mb-3']//descendant::*[@id='subject']",
            MESSAGE_INPUT = "//*[@class='mb-3']//descendant::*[@id='message']",
            SUBMIT_MESSAGE_BUTTON = "//*[@class='button margin-top-0 w-100'] [@type='submit'] [@id='submit']",
            YOUR_MESSAGE_SENT_NOTIFICATION = "//*[@class='col-xl-4 col-lg-4 col-md-12']//descendant::*[@class='closeable notification contact-notification success']",
            YOUR_MESSAGE_SENT_NOTIFICATION_CLOSE_BUTTON = "//*[@class= 'closeable notification contact-notification success']//descendant::*[@class='close']",
            USER_EMAIL = "alinataksa.testing@gmail.com",
            USER_PASSWORD = "Qwerty12345",
            PARTICIPANT1 = "//*[@class='participant-details']//descendant::*[text() = 'Alina Taksa']",
            TEST_CONNECTION_GROUP = "//*[@class='simplebar-content']//descendant::*[@data-id = '30082da1c5e2497f8c12b5416651dcbd']",
            DASHBOARD_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/index/']",
            MY_WORKSPACE_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/session-private.php']",
            NEW_MEETING_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = '#start-session-dialog']",
            PENDING_REQUESTS_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/pending-requests/']",
            MY_CONNECTIONS_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/client-list/']",
            CONNECTION_GROUP_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/connection-groups/']",
            CALENDAR_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/calendar/']",
            UPCOMING_SESSION_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/upcoming-sessions/']",
            SETTINGS_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/settings/']",
            BILLING_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'dashboard/billing/']",
            LOGOUT_OPTION = "//*[@class='dashboard-nav-inner']//descendant::*[@href = 'helpers/logout.php']",
            BUSINESS_PAGE_HEADER = "//*[@class='item-description']//descendant::*[@class='item-description-headline main-page-title-side']",
            HOME_BUTTON = "Home",
            PRICING_BUTTON = "//*[@class='left-side']//descendant::*[@href = '/dashboard/pricing-plans']",
            CONTACT_US_BUTTON = "Contact Us",
            NOTIFICATION_BUTTON = "//*[@class='header-notifications-trigger']//descendant::*[@class='icon-feather-bell']",
            NOTIFICATION_WINDOW = "//*[@class='header-notifications-dropdown']//descendant::*[@class='header-notifications-headline']",
            PERSON_ICON = "//img[@src= 'images/user-avatar-placeholder.png']",
            XPERTESY_LOGO = "//*[@class='left-side']//descendant::*[@href='index']",
            CONTACT_US_HEADER = "//*[@class='col-md-12']//descendant::*[text() = 'Contact Us']",
            CREATE_BUTTON = "//*[@class='dashboard-headline']//descendant::*[@class='connection-session-dialog button popup-with-zoom-anim ripple-effect']",
            CREATE_NEW_GROUP_HEADER = "//*[@class='welcome-text']//descendant::*[text()='Create New Group']",
            CREATE_NEW_GROUP_INPUT_FIELD = "//input[@type='text'] [@class='with-border group-name']",
            CREATE_GROUP_BUTTON = "//*[@class='copy-submit-box margin-top-25 mb-0 submit-field']//descendant::*[@type='submit']",
            YOUR_CONNECTION_GROUP_CREATED_NOTIFICATION_CLOSE_BUTTON = "//button[@title='Close (Esc)'] [@type='button'] [@class='close-success mfp-close']",
            TODAY_BUTTON = "//*[@class='fc-right']//descendant::*[@type='button']",
            BILLING_HEADER = "//*[@class='dashboard-content-inner']//descendant::*[@class='dashboard-headline']",
            DASHBOARD_PAGE_HEADER = "//*[@class='dashboard-content-inner']//descendant::*[@class='dashboard-headline']",
            INVITE_BUTTON = "//*[@class='dashboard-headline']//descendant::*[@class='button ripple-effect invite-connection']",
            SUCCESS_TEXT = "//*[@class='mt-5 text-center']//descendant::*[text()='Copy and send the link']",
            JOIN_SESSION_BUTTON = "//button[@class='margin-top-15 button full-width button-sliding-icon ripple-effect'] [@id='btn-enter-session-preview']",
            PLACEHOLDER_BUTTON = "//a[@class='text-underline'] [@id='placeholder-image-upload']",
            SETTINGS_BUTTON = "//a[@class='text-underline'] [@id='av-preview-open-settings'] [@onclick='previewDialogOpenSettings']",
            VOLUME_CONTROL = "//input[@id='session-video-volume-preview'] [@name='session-video-volume-preview'] [@type='range']",
            AUDIO_ONLY_OPTION = "//*[@class='selection-box'] [@id='video-muted'] [@data-selection='1']",
            AUDIO_AND_VIDEO_OPTION = "//*[@class='selection-box-icon']//descendant::*[@class='d-inline-block icon-feather-video mr-3']",
            MUTE_ALL_OPTION = "//*[@class='selection-box-icon']//descendant::*[@class='d-inline-block icon-feather-video-off mr-3']",
            SKIP_PREVIEW_DIALOG_CHECK_BOX = "//*[@class='checkbox margin-top-15']//descendant::*[@class='checkbox-icon']",
            DUO_CAMERA_SWITCH_BUTTON = "//*[@class='switch lh-1 mb-0']//descendant::*[@class='switch-button']",
            MY_WORKSPACE_SESSION_TITLE = "//*[@class='dashboard-nav-container']//descendant::*[@id='session-title-top']",
            PENDING_REQUESTS_WINDOW_HEADLINE = "//*[@class='col-xl-12']//descendant::*[@class='headline']",
            PRICING_PLANS_HEADER = "//*[@class='col-md-12']//descendant::*[text() = 'Pricing Plans']",
            SETTINGS_HEADER = "//*[@class='col-xl-12']//descendant::*[@class='dashboard-box margin-top-0']",
            SESSION_HEADER = "//*[@class='dashboard-content-inner']//descendant::*[@class='dashboard-headline']",
            LEARN_MORE_PAGE_URL = "https://xpertesy.com/biz/index",
            SIGN_UP_BUTTON = "//*[@class='right-side']//descendant::*[@class = 'popup-with-zoom-anim button ripple-effect margin-left-5 margin-top-20 main-header-login-signup']",
            PAGE_UP_BUTTON = "//*[@class='visible']//descendant::*[@href='#']",
            NEW_SESSION_WITH = "//*[@class='popup-tabs-container']//descendant::*[@id='start-session-step-1']",
            MY_CONNECTION_OPTION = "//*[@class='category-box-icon']//descendant::*[@class='icon-feather-users']",
            GUEST_OPTION = "//*[@class='category-box-icon']//descendant::*[@class='icon-line-awesome-user-secret']",
            YOU_HAVE_NO_CONNECTION_YET_NOTIFICATION = "//*[@class='mt-5 text-center']//descendant::*[@class='tick-container']",
            BACK_BUTTON = "//*[@class='padding-bottom-0 padding-top-40 popup-tab-content']//descendant::*[@class = 'modal-back']",
            NEXT_BUTTON = "//*[@class='copy-submit-box margin-bottom-0 margin-top-0 submit-field']//descendant::*[@class = 'margin-top-0 button full-width button-sliding-icon ripple-effect start-session selection-invitation']",
            TITLE_INPUT_FIELD = "//*[@class='mb-0 submit-field']//descendant::*[@class = 'with-border session-title']",
            NOW_START_OPTION = "//*[@class='radio']//descendant::*[@class = 'radio-label']",
            LATER_START_OPTION = "//*[@class='radio']//descendant::*[@for = 'radio-2']",
            DATE_INPUT_FIELD = "//*[@class='col-6']//descendant::*[@placeholder = 'Date']",
            CALENDAR = "//*[@class='table-condensed']//descendant::*[@data-date = '1669680000000']",
            TIME_INPUT_FIELD = "//*[@class='col-6']//descendant::*[@placeholder = 'Time']",
            CONNECTIONS = "//*[@class='margin-bottom-10 margin-top-5 participant-type-selection']//descendant::*[@class = 'selected']",
            CONNECTIONS_GROUP = "//*[@class='margin-bottom-10 margin-top-5 participant-type-selection']//descendant::*[text() = 'Connections Groups']";

}

